I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 827, in script
    Linus "Sure, you can have a job, just show us proof of citizenship and you're ready to go!"
Exception: Sayer 'Linus' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 827, in script
    Linus "Sure, you can have a job, just show us proof of citizenship and you're ready to go!"
  File "R:\Tools\renpy-7.1.0-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "R:\Tools\renpy-7.1.0-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Linus' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.0.882
CS Bounciness Vol. 3 1.0
Wed Feb 26 21:11:50 2020
